name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-default-inputs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
      
      - name: Default inputs
        uses: ./
        
      - name: Test results
        run: python -c "import trove_classifiers"
      
