name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-default-inputs:
    name: "test default inputs"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Default inputs
        uses: ./

      - name: Test results
        run: python -c "import trove_classifiers"

  test-python:
    name: "test `python`"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Specify `python`
        uses: ./
        with:
          python: "python3.9"

      - name: Test results
        run: python3.9 -c "import trove_classifiers"

  test-requirements-file:
    name: "test `requirements-file`"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Specify `requirements-file`
        uses: ./
        with:
          requirements-file: "requirements.txt"

      - name: Test results
        run: python -c "import trove_classifiers"

  test-options:
    name: "test `options`"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Specify `options`
        uses: ./
        with:
          options: "--target install-target"

      - name: Test results
        run: |
          cd install-target
          test -d trove_classifiers
        shell: bash
